import type { ComposerAnalyticsSegmentRow } from "./types";

export const MOCK_COMPOSER_ANALYTICS_ROWS: ComposerAnalyticsSegmentRow[] = [
  {
    timeframe: "7d",
    postType: "user_post",
    hasMedia: false,
    openCount: 640,
    typingStartCount: 432,
    attachMediaCount: 0,
    cropAppliedCount: 0,
    submitSuccessCount: 228,
    submitFailureCount: 52,
    draftRestoredCount: 94,
    draftRestoredSuccessCount: 33,
    abandonedDraftCount: 42,
    avgTimeToPostSec: 92,
    validationFailures: { text_too_short: 18, max_images: 0, pending_crop: 0, network_error: 10, unknown: 5 },
  },
  {
    timeframe: "7d",
    postType: "user_post",
    hasMedia: true,
    openCount: 320,
    typingStartCount: 238,
    attachMediaCount: 186,
    cropAppliedCount: 121,
    submitSuccessCount: 158,
    submitFailureCount: 29,
    draftRestoredCount: 44,
    draftRestoredSuccessCount: 18,
    abandonedDraftCount: 16,
    avgTimeToPostSec: 118,
    validationFailures: { text_too_short: 5, max_images: 4, pending_crop: 6, network_error: 8, unknown: 3 },
  },
  {
    timeframe: "7d",
    postType: "reflection",
    hasMedia: false,
    openCount: 510,
    typingStartCount: 371,
    attachMediaCount: 0,
    cropAppliedCount: 0,
    submitSuccessCount: 236,
    submitFailureCount: 44,
    draftRestoredCount: 108,
    draftRestoredSuccessCount: 42,
    abandonedDraftCount: 48,
    avgTimeToPostSec: 127,
    validationFailures: { text_too_short: 13, max_images: 0, pending_crop: 0, network_error: 9, unknown: 4 },
  },
  {
    timeframe: "7d",
    postType: "reflection",
    hasMedia: true,
    openCount: 190,
    typingStartCount: 138,
    attachMediaCount: 121,
    cropAppliedCount: 82,
    submitSuccessCount: 97,
    submitFailureCount: 20,
    draftRestoredCount: 35,
    draftRestoredSuccessCount: 15,
    abandonedDraftCount: 14,
    avgTimeToPostSec: 141,
    validationFailures: { text_too_short: 4, max_images: 3, pending_crop: 5, network_error: 6, unknown: 1 },
  },
  {
    timeframe: "7d",
    postType: "testimony",
    hasMedia: false,
    openCount: 210,
    typingStartCount: 155,
    attachMediaCount: 0,
    cropAppliedCount: 0,
    submitSuccessCount: 86,
    submitFailureCount: 19,
    draftRestoredCount: 27,
    draftRestoredSuccessCount: 8,
    abandonedDraftCount: 11,
    avgTimeToPostSec: 133,
    validationFailures: { text_too_short: 7, max_images: 0, pending_crop: 0, network_error: 4, unknown: 2 },
  },
  {
    timeframe: "7d",
    postType: "testimony",
    hasMedia: true,
    openCount: 96,
    typingStartCount: 72,
    attachMediaCount: 62,
    cropAppliedCount: 37,
    submitSuccessCount: 45,
    submitFailureCount: 11,
    draftRestoredCount: 14,
    draftRestoredSuccessCount: 6,
    abandonedDraftCount: 5,
    avgTimeToPostSec: 156,
    validationFailures: { text_too_short: 2, max_images: 2, pending_crop: 2, network_error: 3, unknown: 1 },
  },
  {
    timeframe: "7d",
    postType: "prayer_request",
    hasMedia: false,
    openCount: 284,
    typingStartCount: 208,
    attachMediaCount: 0,
    cropAppliedCount: 0,
    submitSuccessCount: 124,
    submitFailureCount: 26,
    draftRestoredCount: 46,
    draftRestoredSuccessCount: 16,
    abandonedDraftCount: 21,
    avgTimeToPostSec: 109,
    validationFailures: { text_too_short: 9, max_images: 0, pending_crop: 0, network_error: 6, unknown: 2 },
  },
  {
    timeframe: "7d",
    postType: "quote",
    hasMedia: false,
    openCount: 132,
    typingStartCount: 94,
    attachMediaCount: 0,
    cropAppliedCount: 0,
    submitSuccessCount: 61,
    submitFailureCount: 12,
    draftRestoredCount: 15,
    draftRestoredSuccessCount: 6,
    abandonedDraftCount: 4,
    avgTimeToPostSec: 74,
    validationFailures: { text_too_short: 5, max_images: 0, pending_crop: 0, network_error: 2, unknown: 1 },
  },
  {
    timeframe: "7d",
    postType: "quote",
    hasMedia: true,
    openCount: 54,
    typingStartCount: 38,
    attachMediaCount: 31,
    cropAppliedCount: 18,
    submitSuccessCount: 25,
    submitFailureCount: 8,
    draftRestoredCount: 8,
    draftRestoredSuccessCount: 3,
    abandonedDraftCount: 2,
    avgTimeToPostSec: 88,
    validationFailures: { text_too_short: 1, max_images: 1, pending_crop: 1, network_error: 2, unknown: 1 },
  },

  {
    timeframe: "30d",
    postType: "user_post",
    hasMedia: false,
    openCount: 2520,
    typingStartCount: 1695,
    attachMediaCount: 0,
    cropAppliedCount: 0,
    submitSuccessCount: 900,
    submitFailureCount: 221,
    draftRestoredCount: 338,
    draftRestoredSuccessCount: 119,
    abandonedDraftCount: 151,
    avgTimeToPostSec: 95,
    validationFailures: { text_too_short: 78, max_images: 0, pending_crop: 0, network_error: 41, unknown: 18 },
  },
  {
    timeframe: "30d",
    postType: "user_post",
    hasMedia: true,
    openCount: 1224,
    typingStartCount: 872,
    attachMediaCount: 726,
    cropAppliedCount: 472,
    submitSuccessCount: 593,
    submitFailureCount: 126,
    draftRestoredCount: 147,
    draftRestoredSuccessCount: 64,
    abandonedDraftCount: 64,
    avgTimeToPostSec: 121,
    validationFailures: { text_too_short: 19, max_images: 21, pending_crop: 26, network_error: 33, unknown: 14 },
  },
  {
    timeframe: "30d",
    postType: "reflection",
    hasMedia: false,
    openCount: 2030,
    typingStartCount: 1478,
    attachMediaCount: 0,
    cropAppliedCount: 0,
    submitSuccessCount: 955,
    submitFailureCount: 184,
    draftRestoredCount: 407,
    draftRestoredSuccessCount: 161,
    abandonedDraftCount: 188,
    avgTimeToPostSec: 131,
    validationFailures: { text_too_short: 53, max_images: 0, pending_crop: 0, network_error: 32, unknown: 16 },
  },
  {
    timeframe: "30d",
    postType: "reflection",
    hasMedia: true,
    openCount: 760,
    typingStartCount: 546,
    attachMediaCount: 463,
    cropAppliedCount: 317,
    submitSuccessCount: 402,
    submitFailureCount: 88,
    draftRestoredCount: 143,
    draftRestoredSuccessCount: 63,
    abandonedDraftCount: 56,
    avgTimeToPostSec: 146,
    validationFailures: { text_too_short: 18, max_images: 13, pending_crop: 24, network_error: 19, unknown: 7 },
  },
  {
    timeframe: "30d",
    postType: "testimony",
    hasMedia: false,
    openCount: 790,
    typingStartCount: 581,
    attachMediaCount: 0,
    cropAppliedCount: 0,
    submitSuccessCount: 338,
    submitFailureCount: 86,
    draftRestoredCount: 99,
    draftRestoredSuccessCount: 31,
    abandonedDraftCount: 41,
    avgTimeToPostSec: 138,
    validationFailures: { text_too_short: 26, max_images: 0, pending_crop: 0, network_error: 14, unknown: 8 },
  },
  {
    timeframe: "30d",
    postType: "testimony",
    hasMedia: true,
    openCount: 370,
    typingStartCount: 274,
    attachMediaCount: 226,
    cropAppliedCount: 142,
    submitSuccessCount: 180,
    submitFailureCount: 53,
    draftRestoredCount: 51,
    draftRestoredSuccessCount: 20,
    abandonedDraftCount: 23,
    avgTimeToPostSec: 162,
    validationFailures: { text_too_short: 11, max_images: 10, pending_crop: 14, network_error: 12, unknown: 6 },
  },
  {
    timeframe: "30d",
    postType: "prayer_request",
    hasMedia: false,
    openCount: 1136,
    typingStartCount: 839,
    attachMediaCount: 0,
    cropAppliedCount: 0,
    submitSuccessCount: 488,
    submitFailureCount: 112,
    draftRestoredCount: 176,
    draftRestoredSuccessCount: 67,
    abandonedDraftCount: 82,
    avgTimeToPostSec: 114,
    validationFailures: { text_too_short: 34, max_images: 0, pending_crop: 0, network_error: 23, unknown: 10 },
  },
  {
    timeframe: "30d",
    postType: "quote",
    hasMedia: false,
    openCount: 528,
    typingStartCount: 374,
    attachMediaCount: 0,
    cropAppliedCount: 0,
    submitSuccessCount: 248,
    submitFailureCount: 61,
    draftRestoredCount: 57,
    draftRestoredSuccessCount: 24,
    abandonedDraftCount: 21,
    avgTimeToPostSec: 79,
    validationFailures: { text_too_short: 21, max_images: 0, pending_crop: 0, network_error: 9, unknown: 4 },
  },
  {
    timeframe: "30d",
    postType: "quote",
    hasMedia: true,
    openCount: 210,
    typingStartCount: 149,
    attachMediaCount: 118,
    cropAppliedCount: 75,
    submitSuccessCount: 101,
    submitFailureCount: 33,
    draftRestoredCount: 31,
    draftRestoredSuccessCount: 12,
    abandonedDraftCount: 11,
    avgTimeToPostSec: 94,
    validationFailures: { text_too_short: 5, max_images: 6, pending_crop: 8, network_error: 8, unknown: 3 },
  },
];
